# Generated by Django 3.1.6 on 2021-04-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('trainDataID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('BusinessTravel', models.CharField(max_length=32)),
                ('Department', models.CharField(max_length=32)),
                ('DistanceFromHome', models.FloatField()),
                ('Education', models.IntegerField()),
                ('EducationField', models.CharField(max_length=32)),
                ('EmployeeNumber', models.IntegerField()),
                ('EnvironmentSatisfaction', models.IntegerField()),
                ('Gender', models.CharField(max_length=32)),
                ('JobInvolvement', models.IntegerField()),
                ('JobLevel', models.IntegerField()),
                ('JobRole', models.CharField(max_length=32)),
                ('JobSatisfaction', models.IntegerField()),
                ('MaritalStatus', models.CharField(max_length=32)),
                ('MonthlyIncome', models.IntegerField()),
                ('NumCompaniesWorked', models.IntegerField()),
                ('Over18', models.CharField(max_length=8)),
                ('OverTime', models.CharField(max_length=8)),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField()),
                ('StandardHours', models.IntegerField()),
                ('StockOptionLevel', models.IntegerField()),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField()),
                ('WorkLifeBalance', models.IntegerField()),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users')),
            ],
        ),
    ]
